[package]
name = "five_clique"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
rustc-hash = "1.1.0"
rayon = "1.5.3"
